[package]
name = "abstractive_summary"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
serde_json = "1.0.128"
serde = { version = "1.0.210", features = ["derive"] }
tokenizers = "0.20.0"
candle-core = "0.6.0"
candle-transformers = "0.6.0"
