[package]
name = "convert_to_quantized_model"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
candle-core = "0.6.0"
clap = { version = "4.5.17", features = ["derive"] }
rayon = "1.10.0"
safetensors = "0.4.5"
